# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: yavuz blog
#email: yavuz@yapps.co
description: öğrenirken aldığım notlar
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://yavuz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yavuzyildirim
github_username:  yavuz

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-paginate-v2

highlighter: rouge
paginate_path: "/page:num"

google_analytics: UA-44045877-3
images: '/assets/img'
permalink: /:title/
pagination:
  enabled: true
  per_page: 10
  paginator_path: "home/page:num"
  extension: html
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
github: http://github.com/yavuz
show_excerpts: true # set to true to show excerpts on the homepage
disqus:
    shortname: yavuz-github-io

# exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - README.md
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
